name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup V environment
        uses: nocturlab/setup-vlang-action@v1.1.2
        with:
          v-version: master

      # Build nightly
      - name: Build vlog
        run: v -os windows build vlog.v |
             v -os linux build vlog.v 
             
      # Upload builds as artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: vlog.*
             
             

